# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edfe995d6f6bd7f0cd71054be4282d22860db54530a59e550e5bebf534b0608daf4b811719a811a3f629ea3ec9cb7f3af5a317f0680d47e1207958938b5e1b59
  
  #Stripe key
  stripe_publishable_key: pk_test_EuMBifY02rT9X4MjlVThbNr6
  stripe_secret_key:  sk_test_jYpzxd461YP0bkb3qkr3wwCe

test:
  secret_key_base: a3c34bcce058f9953509507c6f9a248ccfde85345de5a377892f163d5f6f5d1b638ed1169d160178ef3f37d55dc781accd90a245ec7852593dd281ed19ff878f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  stripe_publishable_key: pk_test_EuMBifY02rT9X4MjlVThbNr6
  stripe_secret_key:  sk_test_jYpzxd461YP0bkb3qkr3wwCe
  #stripe_publishable_key: ENV['stripe_publishable_key']
  #stripe_secret_key: ENV['stripe_publishable_key']

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
